config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root "dashboard#dashboard", as: "authenticated_root"
  end

  root "static_pages#landing_page"

  resources :incomes, except: [:show]
  resources :expenses, except: [:show]

  resources :income_categories
  resources :expense_categories


  controller :static_pages do
    get :trouble_page
  end

  controller :dashboard do
    get :dashboard
    get :bank_statement
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end

  def bank_statement
    @tasks = Task.where(user_id: current_user.id).order("created_at DESC")
  end

end

app/views/dashboard/_details.html.erb
<div class="col-md-6 col-md-offset-3">
  <h4 class="font-fira-m text-center heading-text">
    <b>
      <u>No Transaction Till Now.</u>
    </b>
  </h4>
  <hr>
</div>

app/views/dashboard/_egroup.html.erb
<div class="col-md-3">
  <div class="panel panel-primary">
    <div class="panel-heading font-fira-m text-center">Total Expense Records.</div>
    <div class="panel-body text-center">
      <hr>
       <h4 class="font-fira">
         <b><%= Expense.where(user: current_user).count %></b> Records
       </h4>
      <hr>
      <h4 class="font-fira-m">
        <%= link_to '+ Add New', new_expense_path,class: 'btn btn-default form-control' %>
        <%= link_to 'Manage', expenses_path,class: 'btn btn-default form-control' %>
      </h4>
    </div>
  </div>
</div>

<div class="col-md-3">
  <div class="panel panel-primary">
    <div class="panel-heading font-fira-m text-center">Total Expense Category Records.</div>
    <div class="panel-body text-center">
      <hr>
       <h4 class="font-fira">
         <b><%= ExpenseCategory.where(user: current_user).count %></b> Records
       </h4>
      <hr>
      <h4 class="font-fira-m">
        <%= link_to '+ Add New', new_expense_category_path,class: 'btn btn-default form-control' %>
        <%= link_to 'Manage', expense_categories_path,class: 'btn btn-default form-control' %>
      </h4>
    </div>
  </div>
</div>

app/views/dashboard/_history.html.erb
<hr>
  <h4 class="font-fira-m">
    <%= "Your Transaction History. " %><b><%= "(#{current_user.full_name})"%></b>
  </h4>
<hr>

<table class="table table-hover">
  <thead>
    <tr class="font-fira-m">
      <th class="text-center">Transaction Type</th>
      <th class="text-center">Transaction Id</th>
      <th class="text-center">Transaction Amount</th>
      <th class="text-center">Transaction Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @tasks.each do |task| %>
<tr class="font-fira text-center">
  <td><b><%= task.taskable_type %></b></td>
  <td><%= task.taskable_id %></td>
  <td><%= task.amount %></td>
  <td><%= task.date.strftime("%d %B %Y") %></td>
</tr>
<% end %>

app/views/dashboard/_igroup.html.erb
<div class="col-md-3">
  <div class="panel panel-primary">
    <div class="panel-heading font-fira-m text-center">Total Income Records.</div>
    <div class="panel-body text-center">
      <hr>
       <h4 class="font-fira">
         <b><%= Income.where(user: current_user).count %></b> Records
       </h4>
      <hr>
      <h4 class="font-fira-m">
        <%= link_to '+ Add New', new_income_path, class: 'btn btn-default form-control' %>
        <%= link_to 'Manage', incomes_path, class: 'btn btn-default form-control' %>
      </h4>
    </div>
  </div>
</div>


<div class="col-md-3">
  <div class="panel panel-primary">
    <div class="panel-heading font-fira-m text-center">Total Income Category Records.</div>
    <div class="panel-body text-center">
      <hr>
       <h4 class="font-fira">
         <b><%= IncomeCategory.where(user: current_user).count %></b> Records
       </h4>
      <hr>
      <h4 class="font-fira-m">
        <%= link_to '+ Add New', new_income_category_path,class: 'btn btn-default form-control' %>
        <%= link_to 'Manage', income_categories_path,class: 'btn btn-default form-control' %>
      </h4>
    </div>
  </div>
</div>

app/views/dashboard/_top.html.erb
<div class="seperator-px">
</div>

<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading font-fira-m text-center">Total Income Amount Recorded.</div>
    <div class="panel-body text-center">
      <hr>
       <h4 class="font-fira">
         <b><%= Income.where(user: current_user).sum(:amount) %></b>
       </h4>
      <hr>
    </div>
  </div>
</div>

<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading font-fira-m text-center">Total Expense Amount Recorded.</div>
    <div class="panel-body text-center">
      <hr>
       <h4 class="font-fira">
         <b><%= Expense.where(user: current_user).sum(:amount) %></b>
       </h4>
      <hr>
    </div>
  </div>
</div>

app/views/dashboard/bank_statement.html.erb
<% if Task.where(user_id: current_user.id).present? %>
 <%= render 'dashboard/history' %>
<% else %>
 <%= render 'dashboard/details' %>
<% end %>

app/views/dashboard/dashboard.html.erb
<%= render 'dashboard/top' %>
<%= render 'dashboard/igroup' %>
<%= render 'dashboard/egroup' %>