config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root "dashboard#dashboard", as: "authenticated_root"
  end

  root "static_pages#landing_page"

  resources :incomes, except: [:show]
  resources :expenses, except: [:show]

  resources :income_categories
  resources :expense_categories


  controller :static_pages do
    get :trouble_page
  end

  controller :dashboard do
    get :dashboard
    get :bank_statement
  end

end

app/models/income.rb
class Income < ApplicationRecord

  belongs_to :user
  belongs_to :income_category, required: false

  has_many :tasks, as: :taskable, dependent: :destroy

  validates :amount, :category_id , :date, presence: true
  validates :amount, numericality: { greater_than: 0 }

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    if params[:income_category].blank?
     @incomes = Income.where(user: current_user).order("date DESC")
   else
     @category_id = IncomeCategory.find_by(user: current_user, category_name: params[:income_category]).id
     @incomes = Income.where(user: current_user, category_id: @category_id).order("date DESC")
   end
  end

  def new
    @income = Income.new
  end

  def edit
  end

  def create
    @income = Income.new(income_params)
    @income.user_id = current_user.id

    if @income.save
      @income.tasks.create!(user_id: current_user.id, amount: @income.amount, date: @income.date)
      redirect_to incomes_path, notice: 'Income was successfully created.'
    else
      render :new
    end
  end

  def update
    if @income.update(income_params)
      redirect_to incomes_path, notice: 'Income was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @income.destroy
    redirect_to incomes_path, notice: 'Income was successfully destroyed.'
  end

  private

    def set_income
      @income = Income.find(params[:id])
    end

    def income_params
      params.require(:income).permit(:amount, :category_id, :date)
    end

    def check_user
      if @income.user_id != current_user.id
        redirect_to root_url, alert: "Sorry, you are not authorized."
      end
    end

end

app/views/incomes/_details.html.erb
<div class="col-md-6 col-md-offset-3">
  <h4 class="font-fira-m text-center heading-text">
    <b>
      <u>Let's get started with with i-manage.</u>
    </b>
  </h4>
  <hr>
  <h5 class= "text-center static-content-text font-fira">
    To Manage Income Record's, you need to add Income Category first! <br/><br/>
    <%= link_to '+ Add New Income Category', new_income_category_path, class: 'font-fira' %>
  </h5>
  <hr>
</div>

app/views/incomes/_form.html.erb
<%= form_for(@income, :html => { :multipart => true }) do |f| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category_id, class: 'font-fira' %>
    <%= f.collection_select(:category_id, IncomeCategory.where(user: current_user), :id, :category_name, {prompt: "choose a category"},
         {class:"form-control dropdown-toggle font-fira"}) %>
  </div>
  <%= link_to 'Add New Income Category', new_income_category_path %>
  <br/><br/><br/>

  <div class="form-group">
    <%= f.label :amount, class: 'font-fira' %>
    <%= f.number_field :amount, class: 'form-control font-fira' %>
  </div>
  <br/>

  <div class="form-group">
    <%= f.label :date, class: 'font-fira' %>
    <%= f.date_field :date, class: 'form-control font-fira' %>
  </div>
  <br/>

  <div class="actions">
    <%= f.submit class: 'btn btn-default form-control' %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<hr>
<h3 class="font-fira-m">Edit Income Record</h1>
<hr>

<%= render 'form', income: @income %>
<br />

<%= link_to 'Return Back', incomes_path, class: 'font-fira-l' %>

app/views/incomes/index.html.erb
<% if IncomeCategory.where(user: current_user).present? %>

  <hr>
  <h4 class="font-fira-m">Income Record History</h4>
  <hr>

  <% if IncomeCategory.where(user: current_user).count > 1 %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle font-fira" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse Incomes by Category<span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Browse All', incomes_path, class: 'font-fira' %></li>
        <li role="separator" class="divider"></li>
        <% IncomeCategory.where(user: current_user).each do |income_category| %>
         <li><%= link_to income_category.category_name, incomes_path(income_category: income_category.category_name), class: 'font-fira' %></li>
        <% end %>
      </ul>
    </li>
  <% else %>
    <h4 class="font-fira">All Income Records</h4>
  <% end %>

  <hr>

  <table class="table table-hover">
    <thead>
      <tr class="font-fira-m">
        <th class="text-center">Amount</th>
        <th class="text-center">Recorded On</th>
        <th class="text-center">Income Category</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @incomes.each do |income| %>
        <tr class="font-fira text-center">
          <td><b><%= income.amount %></b></td>
          <td><%= income.date.strftime("%d %B %Y") %></td>
          <td><%= link_to IncomeCategory.find(income.category_id).category_name, income_category_path(income.category_id), class: 'font-fira-l' %></td>
          <td><%= link_to 'Edit', edit_income_path(income) %></td>
          <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add New Income Record', new_income_path, class: 'btn btn-default form-control' %>

<% else %>
 <%= render 'incomes/details' %>
<% end %>

app/views/incomes/new.html.erb
<hr>
<h3 class="font-fira-m">Add New Income Record</h1>
<hr>

<%= render 'form', income: @income %>