config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root "dashboard#dashboard", as: "authenticated_root"
  end

  root "static_pages#landing_page"

  resources :incomes, except: [:show]
  resources :expenses, except: [:show]

  resources :income_categories
  resources :expense_categories


  controller :static_pages do
    get :trouble_page
  end

  controller :dashboard do
    get :dashboard
    get :bank_statement
  end

end

app/models/income_category.rb
class IncomeCategory < ApplicationRecord

  belongs_to :user
  has_many :incomes
  validates :category_name, presence: true, length: { minimum:5, maximum:15 }
  validates :description, presence: true, length: { minimum:80, maximum:500 }

end

app/controllers/income_categories_controller.rb
class IncomeCategoriesController < ApplicationController
  before_action :set_income_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user, only: [:show, :edit, :update, :destroy]

  def index
    @income_categories = IncomeCategory.where(user: current_user)
  end

  def show
  end

  def new
    @income_category = IncomeCategory.new
  end

  def edit
  end

  def create
    @income_category = IncomeCategory.new(income_category_params)
    @income_category.user_id = current_user.id

    if @income_category.save
      redirect_to @income_category, notice: 'Income category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @income_category.update(income_category_params)
      redirect_to @income_category, notice: 'Income category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @income_category.destroy
    redirect_to income_categories_url, notice: 'Income category was successfully destroyed.'
  end

  private

    def set_income_category
      @income_category = IncomeCategory.find(params[:id])
    end

    def income_category_params
      params.require(:income_category).permit(:category_name, :description)
    end

    def check_user
      if @income_category.user_id != current_user.id
        redirect_to root_url, alert: "Sorry, you are not authorized."
      end
    end

end

app/views/income_categories/_details.html.erb
<div class="col-md-6 col-md-offset-3">

  <h4 class="font-fira-m text-center heading-text">
    <b>
      <u>Let's get started with with i-manage.</u>
    </b>
  </h4>

  <hr>

  <h5 class= "text-center static-content-text">
    <%= link_to '+ Add New Income Category', new_income_category_path, class: 'font-fira' %>
  </h5>

  <hr>

</div>

app/views/income_categories/_form.html.erb
<%= form_for(income_category) do |f| %>
  <% if income_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income_category.errors.count, "error") %> prohibited this income_category from being saved:</h2>

      <ul>
      <% income_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category_name, class: 'font-fira' %>
    <%= f.text_field :category_name, class: 'font-fira form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'font-fira' %>
    <%= f.text_area :description, class: 'font-fira form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-default form-control' %>
  </div>
<% end %>

app/views/income_categories/edit.html.erb
<hr>
<h3 class="font-fira-m">Edit Income Category</h3>
<hr>

<%= render 'form', income_category: @income_category %>

<br />

<%= link_to 'Return Back', income_categories_path, class: 'font-fira-l' %>

app/views/income_categories/index.html.erb
<% if @income_categories.present? %>
  <hr>
  <h3 class="font-fira-m">Income Categories</h3>
  <hr>

  <table class="table table-hover">
    <thead>
      <tr class="font-fira-m">
        <th class="text-center">Category name</th>
        <th class="text-center">Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @income_categories.each do |income_category| %>
        <tr class="font-fira text-center">
          <td><b><%= income_category.category_name %><b></td>
          <td><%= truncate(income_category.description, length:80) %>....</td>
          <td><%= link_to 'Show', income_category %></td>
          <td><%= link_to 'Edit', edit_income_category_path(income_category) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br/>

  <%= link_to 'Add New Income Category', new_income_category_path, class: 'btn btn-default form-control' %>
<% else %>
  <%= render 'income_categories/details' %>
<% end %>

app/views/income_categories/new.html.erb
<hr>
<h3 class="font-fira-m">Add New Income Category</h3>
<hr>

<%= render 'form', income_category: @income_category %>

app/views/income_categories/show.html.erb
<hr>
<h4 class="font-fira-m">Income Category Description</h4>
<hr>

<p>
  <b><h5 class="font-fira-m">Category name</h4></b>
  <h5 class="font-fira"><%= @income_category.category_name %></h5>
</p>

<hr>

<p>
  <b><h5 class="font-fira-m">Description</h5></b>
  <h5 class="font-fira"><%= @income_category.description %></h5>
</p>

<hr>

<%= link_to 'Edit', edit_income_category_path(@income_category), class: 'font-fira-l' %> 