config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root "dashboard#dashboard", as: "authenticated_root"
  end

  root "static_pages#landing_page"

  resources :incomes, except: [:show]
  resources :expenses, except: [:show]

  resources :income_categories
  resources :expense_categories


  controller :static_pages do
    get :trouble_page
  end

  controller :dashboard do
    get :dashboard
    get :bank_statement
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    if params[:expense_category].blank?
     @expenses = Expense.where(user: current_user).order("date DESC")
    else
     @category_id = ExpenseCategory.find_by(user: current_user, category_name: params[:expense_category]).id
     @expenses = Expense.where(user: current_user, category_id: @category_id).order("date DESC")
    end
  end

  def new
    @expense = Expense.new
  end

  def edit
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user_id = current_user.id

    if @expense.save
      @expense.tasks.create!(user_id: current_user.id, amount: @expense.amount, date: @expense.date)
      redirect_to expenses_path, notice: 'Expense was successfully created.'
    else
      render :new
    end
  end

  def update
    if @expense.update(expense_params)
      redirect_to expenses_path, notice: 'Expense was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @expense.destroy
    redirect_to expenses_path, notice: 'Expense was successfully destroyed.'
  end

  private

    def set_expense
      @expense = Expense.find(params[:id])
    end

    def expense_params
      params.require(:expense).permit(:amount, :category_id, :date)
    end

    def check_user
      if @expense.user_id != current_user.id
        redirect_to root_url, alert: "Sorry, you are not authorized."
      end
    end

end

app/views/expenses/_details.html.erb
<div class="col-md-6 col-md-offset-3">
  <h4 class="font-fira-m text-center heading-text">
    <b>
      <u>Let's get started with with i-manage.</u>
    </b>
  </h4>
  <hr>
  <h5 class= "text-center static-content-text font-fira">
    To Manage Expense Record's, you need to add Expense Category first! <br/><br/>
    <%= link_to '+ Add New Income Category', new_expense_category_path, class: 'font-fira' %>
  </h5>
  <hr>
</div>

app/views/expenses/_form.html.erb
<%= form_for(expense) do |f| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category_id, class: 'font-fira' %>
    <%= f.collection_select(:category_id, ExpenseCategory.where(user: current_user), :id, :category_name, {prompt: "choose a category"},
         {class:"form-control dropdown-toggle font-fira"}) %>
  </div>
  <%= link_to 'Add New Expense Category', new_expense_category_path %>
  <br/><br/><br/>

  <div class="form-group">
    <%= f.label :amount, class: 'font-fira' %>
    <%= f.number_field :amount, class: 'form-control font-fira' %>
  </div>
  <br />

  <div class="form-group">
    <%= f.label :date, class: 'font-fira' %>
    <%= f.date_field :date, class: 'form-control font-fira' %>
  </div>
  <br/>

  <div class="actions">
    <%= f.submit class: 'btn btn-default form-control' %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<hr>
<h3 class="font-fira-m">Edit Expense Record</h3>
<hr>

<%= render 'form', expense: @expense %>
<br />

<%= link_to 'Return Back', expenses_path, class: 'font-fira-l' %>

app/views/expenses/index.html.erb
<% if ExpenseCategory.where(user: current_user).present? %>
  <hr>
  <h3 class="font-fira-m">Expenses Record History</h1>
  <hr>
  <% if ExpenseCategory.where(user: current_user).count > 1 %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle font-fira" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse Expenses by Category<span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Browse All', expenses_path, class: 'font-fira' %></li>
        <li role="separator" class="divider"></li>
        <% ExpenseCategory.where(user: current_user).each do |expense_category| %>
         <li><%= link_to expense_category.category_name, expenses_path(expense_category: expense_category.category_name), class: 'font-fira' %></li>
        <% end %>
      </ul>
    </li>
  <% else %>
    <h4 class="font-fira">All Expense Records</h4>
  <% end %>
  <hr>

  <table class="table table-hover">
    <thead>
      <tr class="font-fira-m">
        <th class="text-center">Amount</th>
        <th class="text-center">Date</th>
        <th class="text-center">Expense Category</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @expenses.each do |expense| %>
        <tr class="font-fira text-center">
          <td><b><%= expense.amount %></b></td>
          <td><%= expense.date.strftime("%d %B %Y") %></td>
          <td><%= link_to ExpenseCategory.find(expense.category_id).category_name, expense_category_path(expense.category_id), class: 'font-fira-l' %></td>
          <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
          <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Add New Expense Record', new_expense_path, class: 'btn btn-default form-control' %>
<% else %>
  <%= render 'expenses/details' %>
<% end %>

app/views/expenses/new.html.erb
<hr>
<h3 class="font-fira-m">Add New Expense Record</h3>
<hr>

<%= render 'form', expense: @expense %>